version: "2"
services:
  front:
    container_name: eric-front
    image: node:8
    working_dir: /var/www/app
    volumes:
      - ../eric-site/:/var/www/app
      - ../eric-site/node_modules:/var/www/app/node_modules
    command: bash -c 'yarn && yarn run dev'
    ports:
      - "8080:8080"
  admin:
    container_name: eric-admin
    image: node:8
    working_dir: /var/www/app
    volumes:
      - ../scout-cms/:/var/www/app
      - ../scout-cms/node_modules:/var/www/app/node_modules
    command: bash -c 'yarn && yarn run dev'
    ports:
      - "8888:8888"
  api:
    container_name: eric-api
    image: node:8
    working_dir: /var/www/app
    env_file:
      - ../eric-api/.env
    volumes:
      - ../eric-api/:/var/www/app
      - ../eric-api/node_modules:/var/www/app/node_modules
    command: bash -c 'yarn && yarn run dev'
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: eric-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes_from:
      - mongo_data
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: "${DB_USER}"
    #   MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    # command: mongod --auth
  mongo_data:
    container_name: eric-mongo-data
    image: tianon/true
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/backups:/data/backups
  # nginx:
  #   restart: always
  #   container_name: eric-nginx
  #   image: nginx
  #   ports:
  #     - "80:80"
